# Generated by Django 5.0.9 on 2025-05-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaasset',
            name='url',
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='generated_prompt',
            field=models.TextField(default='Placeholder'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='asset_type',
            field=models.CharField(choices=[('image', 'Image')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media_assets/'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='source',
            field=models.CharField(default='stability-ai', max_length=20),
        ),
    ]
