# Generated by Django 5.0.9 on 2025-05-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_mediaasset_url_mediaasset_generated_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoscript',
            name='voice_id',
            field=models.CharField(default='Matthew', max_length=50),
        ),
    ]
